// Code generated by MockGen. DO NOT EDIT.
// Source: access-system-api/internal/service (interfaces: EmbeddingService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEmbeddingService is a mock of EmbeddingService interface.
type MockEmbeddingService struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingServiceMockRecorder
}

// MockEmbeddingServiceMockRecorder is the mock recorder for MockEmbeddingService.
type MockEmbeddingServiceMockRecorder struct {
	mock *MockEmbeddingService
}

// NewMockEmbeddingService creates a new mock instance.
func NewMockEmbeddingService(ctrl *gomock.Controller) *MockEmbeddingService {
	mock := &MockEmbeddingService{ctrl: ctrl}
	mock.recorder = &MockEmbeddingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingService) EXPECT() *MockEmbeddingServiceMockRecorder {
	return m.recorder
}

// AddEmbedding mocks base method.
func (m *MockEmbeddingService) AddEmbedding(arg0 context.Context, arg1 string, arg2 []float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEmbedding", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEmbedding indicates an expected call of AddEmbedding.
func (mr *MockEmbeddingServiceMockRecorder) AddEmbedding(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEmbedding", reflect.TypeOf((*MockEmbeddingService)(nil).AddEmbedding), arg0, arg1, arg2)
}

// DeleteEmbedding mocks base method.
func (m *MockEmbeddingService) DeleteEmbedding(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmbedding", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmbedding indicates an expected call of DeleteEmbedding.
func (mr *MockEmbeddingServiceMockRecorder) DeleteEmbedding(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmbedding", reflect.TypeOf((*MockEmbeddingService)(nil).DeleteEmbedding), arg0, arg1)
}

// ValidateEmbedding mocks base method.
func (m *MockEmbeddingService) ValidateEmbedding(arg0 context.Context, arg1 []float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEmbedding", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateEmbedding indicates an expected call of ValidateEmbedding.
func (mr *MockEmbeddingServiceMockRecorder) ValidateEmbedding(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEmbedding", reflect.TypeOf((*MockEmbeddingService)(nil).ValidateEmbedding), arg0, arg1)
}
